### ISSUE TITLE
解密失败，提示：[Error] 未知错误:  only Standard PDF encryption handler is available

### ISSUE THREAD

**Issue by rainvalley** [skq1998/ScienceDecrypting#6]
解密时提示未知错误，需要解密的书籍为：https://book.sciencereading.cn/shop/book/Booksimple/show.do?id=BFA739B9F2AB2430597FE7BE701C8A2A0000 。我已经将其上传至百度网盘，链接为：https://pan.baidu.com/s/13GdlTvKknHlCuzeD-Yr9wA?pwd=g3u4 ，提取码：g3u4 。

看起来似乎是科学出版社更换了加密方式？

报错信息如下：
```
PS C:\Users\raincorn\Downloads\ScienceDecrypting-master> python .\decrypt.py -i in.pdf -o out.pdf
[Log] 解析源文件....
[Log] 请求密钥...
[Log] 解密DRM信息...
[Log] 解密文件...
[Error] 未知错误:  only Standard PDF encryption handler is available

如果你需要帮助，请复制以下信息到GitHub ( https://github.com/301Moved/ScienceDecrypting/issues/new ) 上提交Issue
----------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\raincorn\Downloads\ScienceDecrypting-master\decrypt.py", line 387, in <module>
    main()
  File "C:\Users\raincorn\Downloads\ScienceDecrypting-master\decrypt.py", line 382, in main
    decrypt_file(options.src, options.dst)
  File "C:\Users\raincorn\Downloads\ScienceDecrypting-master\decrypt.py", line 351, in decrypt_file
    input_ = MyPdfFileReader(temp_fp)
  File "C:\Users\raincorn\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_reader.py", line 1944, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\raincorn\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_reader.py", line 332, in __init__
    self._encryption = Encryption.read(encrypt_entry, id1_entry)
  File "C:\Users\raincorn\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\_encryption.py", line 845, in read
    raise NotImplementedError(
NotImplementedError: only Standard PDF encryption handler is available
```

**Comment by rainvalley** [comment]
问题已解决，尝试使用[这里](https://github.com/skq1998/ScienceDecrypting/issues/2)打包的EXE可执行文件直接进行解密，解密成功。

查看项目的最后PR时间为21年10月，查看报错在pypdf2，因此考虑对pypdf2进行降级。翻阅pip官网的pypdf2包更新历史，发现在这个时间点的包版本为1.26.0，因此卸载后使用`pip install PyPDF2==1.26.0`重新安装pypdf2，问题解决。同时已对[requirements.txt](https://github.com/skq1998/ScienceDecrypting/blob/main/requirements.txt)提起PR，加入对包版本的指定。

**Comment by SHMinger** [comment]
Mac系统上由于pypdf2为3.0版本，在`decrypt.py`中修改了PDFWriter和PDFReader出现了相同的报错，不知道Mac上有没有适合的解决办法。系统：MacOS13，Mac M1

**Comment by SHMinger** [comment]
> 

问题已解决，确实是pypdf2-3.0.0版本不支持
