### ISSUE TITLE
解密失败求助！

### ISSUE THREAD

**Issue by ScienceZone** [skq1998/ScienceDecrypting#7]
请各位网友帮分析一下解密失败的原因，能不能解决，谢谢！以前使用×家图书馆的账号登录访问网络下载的书可以解密，几个月下书却发现×家图书馆网路访问被玩死了，只能通过另一家图书馆远程访问系统访问下载，但是却发现下载的书无法解密，报错，不知是我电脑系统出现的问题，还是网络的原因。错误信息如下：
Traceback (most recent call last):
  File "urllib3\connection.py", line 159, in _new_conn
  File "urllib3\util\connection.py", line 84, in create_connection
  File "urllib3\util\connection.py", line 74, in create_connection
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1285, in request
  File "http\client.py", line 1331, in _send_request
  File "http\client.py", line 1280, in endheaders
  File "http\client.py", line 1040, in _send_output
  File "http\client.py", line 980, in send
  File "urllib3\connection.py", line 187, in connect
  File "urllib3\connection.py", line 171, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000262172F6B50>: Failed to establish a new connection: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 726, in urlopen
  File "urllib3\util\retry.py", line 446, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='159.226.29.160', port=80): Max retries exceeded with url: /DRMMngr/auth.aspx?pn=scienceReading (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000262172F6B50>: Failed to establish a new connection: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui.py", line 53, in decrypt_background
  File "decrypt.py", line 107, in decrypt_file
  File "decrypt.py", line 43, in request_password
  File "requests\api.py", line 116, in post
  File "requests\api.py", line 60, in request
  File "requests\sessions.py", line 533, in request
  File "requests\sessions.py", line 646, in send
  File "requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='159.226.29.160', port=80): Max retries exceeded with url: /DRMMngr/auth.aspx?pn=scienceReading (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000262172F6B50>: Failed to establish a new connection: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。'))

**Comment by ScienceZone** [comment]
【问题找到，自我解答】问题找到了，将原因告诉大家，希望能帮到有需要的网友。
通过搜索错误提示，发现可能是网上所说的端口被占用问题，但是将可能占用端口（开始我以为是80端口）的软件全部结束或卸载，并重启系统，还是有错误，突然想到有可能是杀毒软件的问题，因为我以前遇到过因杀毒软件致使fiddler无法使用的情况，将火绒安全软件退出，完美解密！
